# General parameters
title: Konev Alexey Sergeevich
email: at.thealchemist@gmail.com
description: >-
  24 y.o developer with glowing <span class="color-red">red</span> eyes
baseurl: ""
url: "https://atthealchemist.github.io"
tg_username: atthealchemist
github_username:  atthealchemist
ready_for_relocation: true

languages: ["ru", "en", "de"]
lang: "ru"

plugins:
  - jekyll-get-json

# Build settings
theme: jekyll-theme-primer

jekyll_get_json:
  - data: github
    json: https://api.github.com/users/atthealchemist/repos/
    cache: true
  - data: bitbucket
    json: https://api.bitbucket.org/2.0/repositories/the-alchemist/
    cache: true

include:
  - pages/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/