stack_full:
  - title:
      ru: Языки программирования
      en: PLs
      de: PSn
    technologies:
      - Python 3.7+
      - C++11
      - C# 7+
      - Java 7+
      - JavaScript
      - EcmaScript 6
      - TypeScript

  - title:
      ru: Разработка пользовательских интерфейсов
      en: UIs
      de: UIs
    technologies:
      - JavaFX
      - WPF
      - Windows Forms
      - Qt 5
      - PyQt 5
      - tkinter
      - Electron

  - title:
      ru: Разработка веб-приложений
      en: Web
      de: Web
    technologies:
      - Flask
      - Django
      - Vibora
      - FastAPI
      - Starlette
      - .NET Core
      - .NET MVC 5
      - Jekyll

  - title:
      ru: Web-серверы
      en: Servers
      de: Servers
    technologies:
      - Nginx
      - Tornado
      - Uvicorn
      - Aiohttp
      - Starlette

  - title:
      ru: Базы данных
      en: DBs
      de: DBs
    technologies:
      - PostgreSQL 10+
      - MySQL (MariaDB)
      - MongoDB
      - Redis
      - Memcached

  - title:
      ru: Очереди сообщений (брокеры)
      en: MQs
      de: MQs
    technologies:
      - Apache Kafka
      - RabbitMQ (Celery)

  - title:
      ru: APIs
      en: APIs
      de: APIs
    technologies:
      - REST
      - SOAP
      - WebSockets
      - Protobuf
      - XML-RPC
      - JSON-RPC

  - title:
      ru: Фронтэнд
      en: Frontend
      de: Frontend
    technologies:
      - HTML 5
      - React
      - CSS 3
      - Angular

  - title:
      ru: CI/CD
      en: CI/CD
      de: CI/CD
    technologies:
      - Gitlab CI
      - Github Actions CI

  - title:
      ru: Операционные системы
      en: OS
      de: OS
    technologies:
      - Windows 7-10 и Server
      - GNU\Linux Debian 7+
      - Arch Linux
      - Gentoo
      - Ubuntu 14+
      - Linux Mint 16+

  - title:
      ru: Разработка мобильных приложений
      en: Mobile
      de: Mobile
    technologies:
      - Android 4.1 - 5.0 (Java)
stack_favorite:
  - Python 3.7+
  - EcmaScript 6
  - FastAPI
  - aiohttp
  - EcmaScript 6