name: deploy-site
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
        with:
          github_token: a24a246f59d1469d2fc4224385c4a333c5cdad3f